### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by heimdall-asguard** [coinbase/rosetta-specifications#1]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/rosetta-specifications/compare/aaabfb57425c44803b607e15210a378f9bd3cf60...aaabfb57425c44803b607e15210a378f9bd3cf60) was merged to master by patrick-ogrady.

Comment with appropriate number of :+1: to approve.

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1
------------ | -------------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/rosetta-specifications&ref=aaabfb57425c44803b607e15210a378f9bd3cf60)

**Comment by annieke** [comment]
:+1:

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1
------------ | -------------
annieke | 1

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/rosetta-specifications&ref=aaabfb57425c44803b607e15210a378f9bd3cf60)

**Comment by brockmiller** [comment]
👍

**Comment by heimdall-asguard** [comment]
Review Error for brockmiller @ 2020-04-28 15:53:47 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Comment by brockmiller** [comment]
👍

**Comment by heimdall-asguard** [comment]
Reviews      | 2/1
------------ | -------------
annieke | 1
brockmiller | 1

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/rosetta-specifications&ref=aaabfb57425c44803b607e15210a378f9bd3cf60)
