### ISSUE TITLE
rosetta-bitcoin and rosetta-ethereum return invalid response on /network/options request

### ISSUE THREAD

**Issue by dvc94ch** [coinbase/rosetta-specifications#111]
The rosetta-bitcoin and rosetta-ethereum set the `call_methods` and `balance_exemptions` to null. The spec mandates a type of `array`.  It seems like the correct thing to do would be to set the fields to `nullable` in the spec or return empty arrays in the implementations. Alternatively it would be even better to make the fields optional, but that's a backwards compatibility issue.

**Comment by GeekArthur** [comment]
Thanks for the callout. The rosetta-bitcoin and rosetta-ethereum should update `call_methods` and `balance_exemptions` to zero value (empty array) to comply rosetta spec. I created two issues for them accordingly:
* https://github.com/coinbase/rosetta-bitcoin/issues/126
* https://github.com/coinbase/rosetta-ethereum/issues/137

I will close this issue and the issue tracking and fix will be moved to the specific rosetta implementations.
