### ISSUE TITLE
TypeScript type generation

### ISSUE THREAD

**Issue by kyranjamie** [coinbase/rosetta-specifications#15]
Great work putting together a blockchain api standard so far @patrick-ogrady and co 👍 

One feature I'm particularly interested in would be to generate typing info from the model files. Doing so leverages tooling many are already using, and can facilitate a much better DX.

We're already doing this @blockstack with our [api layer that sits atop our code node](https://github.com/blockstack/stacks-blockchain-sidecar/blob/master/docs/scripts/generate-types.ts), and publishing a [package of the output types](https://www.npmjs.com/package/@blockstack/stacks-blockchain-sidecar-types).

It's not a perfect set up. It uses a mash of npm packages, and has ran into some limitations of the JSON Schema standard. Primarily: How should you generate types with `allOf` and `oneOf` properties, as well as types with 2 or more discriminating type unions. But otherwise has served us quite well.

Would love to hear whether this has already been discussed, and thoughts on how it could fit into the Rosetta project.

**Comment by patrick-ogrady** [comment]
We have only done this for Golang thus far...[rosetta-sdk-go](https://https://github.com/coinbase/rosetta-sdk-go). Check out the [types package](https://github.com/coinbase/rosetta-sdk-go/tree/master/types)!

If you are interested in doing the same for JS, TS, or any other language, I'm sure others in the community would use it extensively. We already received 1 question about this in our [Discourse](https://community.rosetta-api.org/t/any-plans-for-a-js-sdk/32/2).

I wrote up a little blurb explaining the decision to start with Golang [here](https://github.com/coinbase/rosetta-specifications#sdks-in-more-languages).

**Comment by AlanVerbner** [comment]
@kyranjamie we are using https://www.npmjs.com/package/dtsgenerator to generate typescript type definitions based on `api.json` file, something like `dtsgen --out ./types/rosetta-types.d.ts ./rosetta-specifications/api.json`

**Comment by sp6pe** [comment]
@AlanVerbner Would be cool if you created a Typescript SDK! We'd be happy to post it on the main website and community page!
