### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by heimdall-asguard** [coinbase/rosetta-specifications#4]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/rosetta-specifications/compare/7133323548af6d72f46539e306d4fb8174e7d48c...c3b97c3f24a9d85b5aee111a561157b852340fe8) was merged to master by patrick-ogrady.

Comment with appropriate number of :+1: to approve.

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1
------------ | -------------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/rosetta-specifications&ref=c3b97c3f24a9d85b5aee111a561157b852340fe8)

**Comment by annieke** [comment]
👍

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1
------------ | -------------
annieke | 1

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/rosetta-specifications&ref=c3b97c3f24a9d85b5aee111a561157b852340fe8)
