### ISSUE TITLE
Add "Total Count" to Indexer Search Transactions Response

### ISSUE THREAD

**Issue by stuartkuentzel** [coinbase/rosetta-specifications#69]
Usually for paginated responses, a "total count" is available. Since there are offset and limit params, adding `total_count` to [SearchTransactionsResponse](https://www.rosetta-api.org/docs/models/SearchTransactionsResponse.html) would be helpful, especially when querying for address transactions.

**Comment by patrick-ogrady** [comment]
This makes sense to me, @stuartkuentzel! I've created an internal ticket and will include this in the next release.
